export const ActionTypes = {
    SET_USER:"SET_USER",
    SIGN_OUT_USER: "SIGN_OUT_USER",
    SET_BILLS: "SET_BILLS",
    SET_CUSTOMERS: "SET_CUSTOMERS",
    SET_PRODUCTS: "SET_PRODUCTS",
    SET_SUPPLIERS: "SET_SUPPLIERS", 
}